"""added the group size and country in registration data

Revision ID: 17aa7e1948d3
Revises: 62f9cb00849a
Create Date: 2026-01-11 15:38:22.193649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17aa7e1948d3'
down_revision = '62f9cb00849a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_size', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.drop_column('group_size')

    # ### end Alembic commands ###
