"""empty message

Revision ID: 1f5f8990687e
Revises: 133655e65749
Create Date: 2025-11-28 05:41:04.357325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1f5f8990687e'
down_revision = '133655e65749'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_attendee_checkin'))
        batch_op.drop_index(batch_op.f('ix_attendee_registrations_checked_in'))
        batch_op.drop_column('badge_printed')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('checked_in_by')
        batch_op.drop_column('checked_in')

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_by', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('badge_printed', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_checkin', ['checked_in', 'checked_in_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_registrations_checked_in'), ['checked_in'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registrations_checked_in'))
        batch_op.drop_index('idx_checkin')
        batch_op.drop_column('badge_printed')
        batch_op.drop_column('checked_in_by')
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('checked_in')

    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checked_in_by', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('badge_printed', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_attendee_registrations_checked_in'), ['checked_in'], unique=False)
        batch_op.create_index(batch_op.f('idx_attendee_checkin'), ['checked_in', 'checked_in_at'], unique=False)

    # ### end Alembic commands ###
