"""Add DPO payment gateway fields to Payment model

Revision ID: 62f9cb00849a
Revises: fix_enum_20251129
Create Date: 2025-12-04 13:07:28.277499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62f9cb00849a'
down_revision = 'fix_enum_20251129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dpo_trans_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dpo_trans_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dpo_result_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dpo_result_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dpo_payment_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_dpo_trans_ref'), ['dpo_trans_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_dpo_trans_token'), ['dpo_trans_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_dpo_trans_token'))
        batch_op.drop_index(batch_op.f('ix_payments_dpo_trans_ref'))
        batch_op.drop_column('dpo_payment_type')
        batch_op.drop_column('dpo_result_explanation')
        batch_op.drop_column('dpo_result_code')
        batch_op.drop_column('dpo_trans_ref')
        batch_op.drop_column('dpo_trans_token')

    # ### end Alembic commands ###
