"""Add group_size field to attendee_registrations

Revision ID: 876d495dc419
Revises: 17aa7e1948d3
Create Date: 2026-01-11 16:47:16.234528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876d495dc419'
down_revision = '17aa7e1948d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_size', sa.Integer(), nullable=True))
        batch_op.alter_column('professional_category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('farmer', 'researcher_academic', 'student', 'government_official', 'ngo_nonprofit', 'private_sector', 'entrepreneur', 'consultant', 'extension_officer', 'cooperative_member', 'investor', 'media_journalist', 'policy_maker', 'conservationist', 'educator', 'other', name='professionalcategory'),
               existing_nullable=True)

    with op.batch_alter_table('exhibitor_registrations', schema=None) as batch_op:
        batch_op.alter_column('industry_category',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('AGRICULTURE_INPUTS', 'EQUIPMENT_MACHINERY', 'PROCESSING_PACKAGING', 'TECHNOLOGY_INNOVATION', 'FINANCIAL_SERVICES', 'TRAINING_EDUCATION', 'RESEARCH_DEVELOPMENT', 'CONSULTING_ADVISORY', 'CONSERVATION_ENVIRONMENT', 'CERTIFICATION_STANDARDS', 'LOGISTICS_SUPPLY_CHAIN', 'MARKETING_TRADE', 'GOVERNMENT_AGENCY', 'NGO_DEVELOPMENT', 'MEDIA_COMMUNICATIONS', 'HEALTHCARE_NUTRITION', 'TOURISM_HOSPITALITY', 'OTHER', name='industrycategory'),
               existing_nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_type', sa.Enum('INITIAL', 'PARTIAL', 'BALANCE', 'REFUND', 'RETRY', name='paymenttype'), nullable=False))
        batch_op.add_column(sa.Column('dpo_trans_token', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dpo_trans_ref', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('dpo_result_code', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('dpo_result_explanation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('dpo_payment_type', sa.String(length=20), nullable=True))
        batch_op.create_index(batch_op.f('ix_payments_dpo_trans_ref'), ['dpo_trans_ref'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_dpo_trans_token'), ['dpo_trans_token'], unique=False)

    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_checkin'))
        batch_op.drop_index(batch_op.f('ix_registrations_checked_in'))
        batch_op.drop_column('checked_in_at')
        batch_op.drop_column('checked_in')
        batch_op.drop_column('checked_in_by')
        batch_op.drop_column('badge_printed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('badge_printed', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_by', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('checked_in', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('checked_in_at', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('ix_registrations_checked_in'), ['checked_in'], unique=False)
        batch_op.create_index(batch_op.f('idx_checkin'), ['checked_in', 'checked_in_at'], unique=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_dpo_trans_token'))
        batch_op.drop_index(batch_op.f('ix_payments_dpo_trans_ref'))
        batch_op.drop_column('dpo_payment_type')
        batch_op.drop_column('dpo_result_explanation')
        batch_op.drop_column('dpo_result_code')
        batch_op.drop_column('dpo_trans_ref')
        batch_op.drop_column('dpo_trans_token')
        batch_op.drop_column('payment_type')

    with op.batch_alter_table('exhibitor_registrations', schema=None) as batch_op:
        batch_op.alter_column('industry_category',
               existing_type=sa.Enum('AGRICULTURE_INPUTS', 'EQUIPMENT_MACHINERY', 'PROCESSING_PACKAGING', 'TECHNOLOGY_INNOVATION', 'FINANCIAL_SERVICES', 'TRAINING_EDUCATION', 'RESEARCH_DEVELOPMENT', 'CONSULTING_ADVISORY', 'CONSERVATION_ENVIRONMENT', 'CERTIFICATION_STANDARDS', 'LOGISTICS_SUPPLY_CHAIN', 'MARKETING_TRADE', 'GOVERNMENT_AGENCY', 'NGO_DEVELOPMENT', 'MEDIA_COMMUNICATIONS', 'HEALTHCARE_NUTRITION', 'TOURISM_HOSPITALITY', 'OTHER', name='industrycategory'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('attendee_registrations', schema=None) as batch_op:
        batch_op.alter_column('professional_category',
               existing_type=sa.Enum('farmer', 'researcher_academic', 'student', 'government_official', 'ngo_nonprofit', 'private_sector', 'entrepreneur', 'consultant', 'extension_officer', 'cooperative_member', 'investor', 'media_journalist', 'policy_maker', 'conservationist', 'educator', 'other', name='professionalcategory'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('group_size')

    # ### end Alembic commands ###
