"""add consent_catalog column to registrations

Revision ID: a53412520dbf
Revises: dc20d9f3bad0
Create Date: 2026-03-03 15:08:23.501914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a53412520dbf'
down_revision = 'dc20d9f3bad0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('consent_catalog', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('consent_catalog')

    # ### end Alembic commands ###
