"""Add resume OTP fields to registrations

Revision ID: c79332f48b9f
Revises: f8a2c3d91e47
Create Date: 2026-04-03 06:27:19.982925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79332f48b9f'
down_revision = 'f8a2c3d91e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resume_otp', sa.String(length=6), nullable=True))
        batch_op.add_column(sa.Column('resume_otp_expires', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resume_otp_attempts', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('resume_otp_attempts')
        batch_op.drop_column('resume_otp_expires')
        batch_op.drop_column('resume_otp')

    # ### end Alembic commands ###
